//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPPMM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPPMM.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application contains the following open source softwares..
        /// </summary>
        public static string ContainsLicense {
            get {
                return ResourceManager.GetString("ContainsLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - - -.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera is under processing. Try again after a while..
        /// </summary>
        public static string ErrorMessage_cameraNotReady {
            get {
                return ResourceManager.GetString("ErrorMessage_cameraNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find SSID or/and Password from the NFC tag..
        /// </summary>
        public static string ErrorMessage_CantFindSonyRecord {
            get {
                return ResourceManager.GetString("ErrorMessage_CantFindSonyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote request failed..
        /// </summary>
        public static string ErrorMessage_fatal {
            get {
                return ResourceManager.GetString("ErrorMessage_fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error has occured while downloading your picture..
        /// </summary>
        public static string ErrorMessage_ImageDL_Network {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error has occured..
        /// </summary>
        public static string ErrorMessage_ImageDL_Other {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error has occured. Please try again with smaller image size to transfer..
        /// </summary>
        public static string ErrorMessage_ImageDL_OtherOriginal {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_OtherOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the picture..
        /// </summary>
        public static string ErrorMessage_ImageDL_Saving {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the picture. Please try again with smaller image size to transfer..
        /// </summary>
        public static string ErrorMessage_ImageDL_SavingOriginal {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_SavingOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Stopped interval shooting..
        /// </summary>
        public static string ErrorMessage_Interval {
            get {
                return ResourceManager.GetString("ErrorMessage_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read data from the NFC tag..
        /// </summary>
        public static string ErrorMessage_ParseNFC {
            get {
                return ResourceManager.GetString("ErrorMessage_ParseNFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to shoot or start recording. Make sure of the camera device&apos;s status..
        /// </summary>
        public static string ErrorMessage_shootingFailure {
            get {
                return ResourceManager.GetString("ErrorMessage_shootingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timeout. Make sure of the Wi-Fi connection and try again..
        /// </summary>
        public static string ErrorMessage_timeout {
            get {
                return ResourceManager.GetString("ErrorMessage_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find the devide. Make sure that SSID of connected access point is that of your camera device&apos;s..
        /// </summary>
        public static string Guide_CantFindDevice {
            get {
                return ResourceManager.GetString("Guide_CantFindDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Wi-Fi password of the camera device?
        ///You can touch your NFC enabled phone to NFC enabled camera to find password of Wi-Fi..
        /// </summary>
        public static string Guide_NFC {
            get {
                return ResourceManager.GetString("Guide_NFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe to start remote control..
        /// </summary>
        public static string Guide_StartLiveView {
            get {
                return ResourceManager.GetString("Guide_StartLiveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Wi-Fi settings and connect to your camera device..
        /// </summary>
        public static string Guide_WiFiNotEnabled {
            get {
                return ResourceManager.GetString("Guide_WiFiNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string IntervalCountPrefix {
            get {
                return ResourceManager.GetString("IntervalCountPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval shooting.
        /// </summary>
        public static string IntervalSetting {
            get {
                return ResourceManager.GetString("IntervalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval (sec.).
        /// </summary>
        public static string IntervalTime {
            get {
                return ResourceManager.GetString("IntervalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string IntervalTimePrefix {
            get {
                return ResourceManager.GetString("IntervalTimePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The picture has been captured successfully!.
        /// </summary>
        public static string Message_ImageCapture_Succeed {
            get {
                return ResourceManager.GetString("Message_ImageCapture_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The picture has been saved successfully!.
        /// </summary>
        public static string Message_ImageDL_Succeed {
            get {
                return ResourceManager.GetString("Message_ImageDL_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open source licenses.
        /// </summary>
        public static string OSSText {
            get {
                return ResourceManager.GetString("OSSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive captured image.
        /// </summary>
        public static string PostviewTransferSetting {
            get {
                return ResourceManager.GetString("PostviewTransferSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/kazyx/WPPMM.
        /// </summary>
        public static string RepoURL {
            get {
                return ResourceManager.GetString("RepoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self timer.
        /// </summary>
        public static string SelfTimer {
            get {
                return ResourceManager.GetString("SelfTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size to receive.
        /// </summary>
        public static string Setting_PostViewImageSize {
            get {
                return ResourceManager.GetString("Setting_PostViewImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation mode.
        /// </summary>
        public static string ShootMode {
            get {
                return ResourceManager.GetString("ShootMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio rec.
        /// </summary>
        public static string ShootModeAudio {
            get {
                return ResourceManager.GetString("ShootModeAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie rec.
        /// </summary>
        public static string ShootModeMovie {
            get {
                return ResourceManager.GetString("ShootModeMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still image rec.
        /// </summary>
        public static string ShootModeStill {
            get {
                return ResourceManager.GetString("ShootModeStill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 MPixels.
        /// </summary>
        public static string Size2M {
            get {
                return ResourceManager.GetString("Size2M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string SizeOriginal {
            get {
                return ResourceManager.GetString("SizeOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        public static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-Fi settings.
        /// </summary>
        public static string WifiSettingLauncherButtonText {
            get {
                return ResourceManager.GetString("WifiSettingLauncherButtonText", resourceCulture);
            }
        }
    }
}
