//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34003
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPPMM.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPPMM.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   about に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PlayNightmare Mobile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイス一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonToDeviceListText {
            get {
                return ResourceManager.GetString("ButtonToDeviceListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリケーションは下記のオープンソースソフトウェアを使用しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContainsLicense {
            get {
                return ResourceManager.GetString("ContainsLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイス一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeviceListTitle {
            get {
                return ResourceManager.GetString("DeviceListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn&apos;t find the devide. Make sure the connected SSID is same as your device&apos;s one. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Guide_CantFindDevice {
            get {
                return ResourceManager.GetString("Guide_CantFindDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect to your device. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Guide_WiFiNotConnected {
            get {
                return ResourceManager.GetString("Guide_WiFiNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wi-Fi設定から、対応したカメラ機器に接続してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Guide_WiFiNotEnabled {
            get {
                return ResourceManager.GetString("Guide_WiFiNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オープンソースライセンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSSText {
            get {
                return ResourceManager.GetString("OSSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://dummy.com/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RepoURL {
            get {
                return ResourceManager.GetString("RepoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LeftToRight に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ja-jp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソースコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スマートリモコン開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRemoteControllingButtonText {
            get {
                return ResourceManager.GetString("StartRemoteControllingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wi-Fi設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WifiSettingLauncherButtonText {
            get {
                return ResourceManager.GetString("WifiSettingLauncherButtonText", resourceCulture);
            }
        }
    }
}
