//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34011
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPPMM.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPPMM.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   about に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppBar_AppSetting {
            get {
                return ResourceManager.GetString("AppBar_AppSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera Roll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppBar_CameraRoll {
            get {
                return ResourceManager.GetString("AppBar_CameraRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unlock AF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppBar_CancelTouchAf {
            get {
                return ResourceManager.GetString("AppBar_CancelTouchAf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scrap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected to _ssid_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectedDevice {
            get {
                return ResourceManager.GetString("ConnectedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This application contains the following open source softwares. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContainsLicense {
            get {
                return ResourceManager.GetString("ContainsLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developed by に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    - - - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display shutter button on the screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayTakeImageButtonSetting {
            get {
                return ResourceManager.GetString("DisplayTakeImageButtonSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Donation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to retrieve information.
        ///Please check internet connection status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_Message_FailedToGetInfo {
            get {
                return ResourceManager.GetString("Error_Message_FailedToGetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera is under processing. Try again after a while. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_cameraNotReady {
            get {
                return ResourceManager.GetString("ErrorMessage_cameraNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn&apos;t find SSID or Password from the NFC tag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_CantFindSonyRecord {
            get {
                return ResourceManager.GetString("ErrorMessage_CantFindSonyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection has been lost. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_Dsconnected {
            get {
                return ResourceManager.GetString("ErrorMessage_Dsconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remote request failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_fatal {
            get {
                return ResourceManager.GetString("ErrorMessage_fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network error has occured while downloading your picture. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_ImageDL_Network {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected error has occured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_ImageDL_Other {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected error has occured. Please try again with smaller image size to transfer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_ImageDL_OtherOriginal {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_OtherOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save the picture. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_ImageDL_Saving {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save the picture. Please try again with smaller image size to transfer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_ImageDL_SavingOriginal {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_SavingOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occured. Stopped interval shooting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_Interval {
            get {
                return ResourceManager.GetString("ErrorMessage_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read data from the NFC tag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_ParseNFC {
            get {
                return ResourceManager.GetString("ErrorMessage_ParseNFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to shoot or start recording. Make sure of the camera device&apos;s status. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_shootingFailure {
            get {
                return ResourceManager.GetString("ErrorMessage_shootingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Request timeout. Make sure of the Wi-Fi connection and try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_timeout {
            get {
                return ResourceManager.GetString("ErrorMessage_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn&apos;t find the devide. Make sure that SSID of connected access point is that of your camera device&apos;s. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Guide_CantFindDevice {
            get {
                return ResourceManager.GetString("Guide_CantFindDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can invoke remote shutter with your phone&apos;s hardware shutter key. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Guide_DisplayTakeImageButtonSetting {
            get {
                return ResourceManager.GetString("Guide_DisplayTakeImageButtonSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can touch your NFC enabled camera to find password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Guide_NFC {
            get {
                return ResourceManager.GetString("Guide_NFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swipe to start remote control. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Guide_StartLiveView {
            get {
                return ResourceManager.GetString("Guide_StartLiveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to Wi-Fi settings and connect to your camera device. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Guide_WiFiNotEnabled {
            get {
                return ResourceManager.GetString("Guide_WiFiNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IntervalCountPrefix {
            get {
                return ResourceManager.GetString("IntervalCountPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval shooting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IntervalSetting {
            get {
                return ResourceManager.GetString("IntervalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval (sec.) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IntervalTime {
            get {
                return ResourceManager.GetString("IntervalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IntervalTimePrefix {
            get {
                return ResourceManager.GetString("IntervalTimePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please acknowledge that NO secret function is unlocked by purchasing these in-app items. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_Caution {
            get {
                return ResourceManager.GetString("Message_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Donation will encourage our development for continuous update! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_Encourage {
            get {
                return ResourceManager.GetString("Message_Encourage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The picture has been captured successfully! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ImageCapture_Succeed {
            get {
                return ResourceManager.GetString("Message_ImageCapture_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The picture has been saved successfully! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ImageDL_Succeed {
            get {
                return ResourceManager.GetString("Message_ImageDL_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wi-Fi password of your camera device has been saved to the clipboard! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NFC_succeed {
            get {
                return ResourceManager.GetString("Message_NFC_succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCaption_error {
            get {
                return ResourceManager.GetString("MessageCaption_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opened successfully! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCaption_NFC_Succeed {
            get {
                return ResourceManager.GetString("MessageCaption_NFC_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please ignore incorrect system prompt!! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NFC_iiwake {
            get {
                return ResourceManager.GetString("NFC_iiwake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open source licenses に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSSText {
            get {
                return ResourceManager.GetString("OSSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receive captured image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostviewTransferSetting {
            get {
                return ResourceManager.GetString("PostviewTransferSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/kazyx/WPPMM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RepoURL {
            get {
                return ResourceManager.GetString("RepoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LeftToRight に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///    seconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Self timer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelfTimer {
            get {
                return ResourceManager.GetString("SelfTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image size to receive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_PostViewImageSize {
            get {
                return ResourceManager.GetString("Setting_PostViewImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShootMode {
            get {
                return ResourceManager.GetString("ShootMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio rec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShootModeAudio {
            get {
                return ResourceManager.GetString("ShootModeAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movie rec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShootModeMovie {
            get {
                return ResourceManager.GetString("ShootModeMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Still image rec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShootModeStill {
            get {
                return ResourceManager.GetString("ShootModeStill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 MPixels に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Size2M {
            get {
                return ResourceManager.GetString("Size2M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SizeOriginal {
            get {
                return ResourceManager.GetString("SizeOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wi-Fi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WifiSettingLauncherButtonText {
            get {
                return ResourceManager.GetString("WifiSettingLauncherButtonText", resourceCulture);
            }
        }
    }
}
