//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kazyx.WPPMM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kazyx.WPPMM.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable geotagging.
        /// </summary>
        public static string AddGeotag {
            get {
                return ResourceManager.GetString("AddGeotag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add geotag to the received photos. Be careful of your privacy when you share them. Note that cellular network is additionally required to obtain location info in some phone devices.﻿.
        /// </summary>
        public static string AddGeotag_guide {
            get {
                return ResourceManager.GetString("AddGeotag_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture.
        /// </summary>
        public static string Aperture {
            get {
                return ResourceManager.GetString("Aperture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AppBar_AppSetting {
            get {
                return ResourceManager.GetString("AppBar_AppSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Roll.
        /// </summary>
        public static string AppBar_CameraRoll {
            get {
                return ResourceManager.GetString("AppBar_CameraRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock AF.
        /// </summary>
        public static string AppBar_CancelTouchAf {
            get {
                return ResourceManager.GetString("AppBar_CancelTouchAf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl Panel.
        /// </summary>
        public static string AppBar_ControlPanel {
            get {
                return ResourceManager.GetString("AppBar_ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string AppBar_Delete {
            get {
                return ResourceManager.GetString("AppBar_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string AppBar_Download {
            get {
                return ResourceManager.GetString("AppBar_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AppBar_Exit {
            get {
                return ResourceManager.GetString("AppBar_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide header.
        /// </summary>
        public static string AppBar_HideHeader {
            get {
                return ResourceManager.GetString("AppBar_HideHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string AppBar_Refresh {
            get {
                return ResourceManager.GetString("AppBar_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show header.
        /// </summary>
        public static string AppBar_ShowHeader {
            get {
                return ResourceManager.GetString("AppBar_ShowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto power off.
        /// </summary>
        public static string AutoPowerOff {
            get {
                return ResourceManager.GetString("AutoPowerOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System sound.
        /// </summary>
        public static string BeepMode {
            get {
                return ResourceManager.GetString("BeepMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter tone only.
        /// </summary>
        public static string BeepModeShutterOnly {
            get {
                return ResourceManager.GetString("BeepModeShutterOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom left corner.
        /// </summary>
        public static string BottomLeft {
            get {
                return ResourceManager.GetString("BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom right corner.
        /// </summary>
        public static string BottomRight {
            get {
                return ResourceManager.GetString("BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in version of Smart Remote Control app could not be supported by 3rd party applications.
        ///Please update to the latest at PlayMemories Camera Apps store..
        /// </summary>
        public static string BuiltInSRNotSupported {
            get {
                return ResourceManager.GetString("BuiltInSRNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string ColorMode_Neutral {
            get {
                return ResourceManager.GetString("ColorMode_Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vivid.
        /// </summary>
        public static string ColorMode_Vivid {
            get {
                return ResourceManager.GetString("ColorMode_Vivid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ColorSetting {
            get {
                return ResourceManager.GetString("ColorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to _ssid_.
        /// </summary>
        public static string ConnectedDevice {
            get {
                return ResourceManager.GetString("ConnectedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application contains the following open source softwares..
        /// </summary>
        public static string ContainsLicense {
            get {
                return ResourceManager.GetString("ContainsLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burst.
        /// </summary>
        public static string ContinuousShootMode_Burst {
            get {
                return ResourceManager.GetString("ContinuousShootMode_Burst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cont. shoot..
        /// </summary>
        public static string ContinuousShootMode_Cont {
            get {
                return ResourceManager.GetString("ContinuousShootMode_Cont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MotionShot.
        /// </summary>
        public static string ContinuousShootMode_MotionShot {
            get {
                return ResourceManager.GetString("ContinuousShootMode_MotionShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string ContinuousShootMode_Single {
            get {
                return ResourceManager.GetString("ContinuousShootMode_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast cont..
        /// </summary>
        public static string ContinuousShootMode_SpeedPriority {
            get {
                return ResourceManager.GetString("ContinuousShootMode_SpeedPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10pic./1.25sec..
        /// </summary>
        public static string ContinuousShootSpeed_FixedFrames_10_In_1_25Sec {
            get {
                return ResourceManager.GetString("ContinuousShootSpeed_FixedFrames_10_In_1_25Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10pic./2sec..
        /// </summary>
        public static string ContinuousShootSpeed_FixedFrames_10_In_2Sec {
            get {
                return ResourceManager.GetString("ContinuousShootSpeed_FixedFrames_10_In_2Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10pic./5sec..
        /// </summary>
        public static string ContinuousShootSpeed_FixedFrames_10_In_5Sec {
            get {
                return ResourceManager.GetString("ContinuousShootSpeed_FixedFrames_10_In_5Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string ContinuousShootSpeed_High {
            get {
                return ResourceManager.GetString("ContinuousShootSpeed_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string ContinuousShootSpeed_Low {
            get {
                return ResourceManager.GetString("ContinuousShootSpeed_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive mode.
        /// </summary>
        public static string ContShootingMode {
            get {
                return ResourceManager.GetString("ContShootingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cont. shooting speed.
        /// </summary>
        public static string ContShootingSpeed {
            get {
                return ResourceManager.GetString("ContShootingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - - -.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display histogram.
        /// </summary>
        public static string DisplayHistogram {
            get {
                return ResourceManager.GetString("DisplayHistogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display shutter button.
        /// </summary>
        public static string DisplayTakeImageButtonSetting {
            get {
                return ResourceManager.GetString("DisplayTakeImageButtonSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation.
        /// </summary>
        public static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve information.
        ///Please check internet connection status.
        /// </summary>
        public static string Error_Message_FailedToGetInfo {
            get {
                return ResourceManager.GetString("Error_Message_FailedToGetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera is under processing. Try again after a while..
        /// </summary>
        public static string ErrorMessage_cameraNotReady {
            get {
                return ResourceManager.GetString("ErrorMessage_cameraNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find SSID or Password from the NFC tag..
        /// </summary>
        public static string ErrorMessage_CantFindSonyRecord {
            get {
                return ResourceManager.GetString("ErrorMessage_CantFindSonyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection has been lost..
        /// </summary>
        public static string ErrorMessage_Dsconnected {
            get {
                return ResourceManager.GetString("ErrorMessage_Dsconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get location info. Original file has been saved..
        /// </summary>
        public static string ErrorMessage_FailedToGetGeoposition {
            get {
                return ResourceManager.GetString("ErrorMessage_FailedToGetGeoposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote request failed..
        /// </summary>
        public static string ErrorMessage_fatal {
            get {
                return ResourceManager.GetString("ErrorMessage_fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original geotag is prior to that of this app. Original file has been saved..
        /// </summary>
        public static string ErrorMessage_ImageDL_DuplicatedGeotag {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_DuplicatedGeotag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add geotag. Original file has been saved..
        /// </summary>
        public static string ErrorMessage_ImageDL_Geotagging {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_Geotagging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch some images by limitation of continuous shooting..
        /// </summary>
        public static string ErrorMessage_ImageDL_Gone {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error has occured while downloading your picture..
        /// </summary>
        public static string ErrorMessage_ImageDL_Network {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error has occured..
        /// </summary>
        public static string ErrorMessage_ImageDL_Other {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error has occured. Please try again with smaller image size to transfer..
        /// </summary>
        public static string ErrorMessage_ImageDL_OtherOriginal {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_OtherOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the picture..
        /// </summary>
        public static string ErrorMessage_ImageDL_Saving {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the picture. Please try again with smaller image size to transfer..
        /// </summary>
        public static string ErrorMessage_ImageDL_SavingOriginal {
            get {
                return ResourceManager.GetString("ErrorMessage_ImageDL_SavingOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Stopped interval shooting..
        /// </summary>
        public static string ErrorMessage_Interval {
            get {
                return ResourceManager.GetString("ErrorMessage_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please turn on location service at system settings for geotagging feature..
        /// </summary>
        public static string ErrorMessage_LocationAccessUnauthorized {
            get {
                return ResourceManager.GetString("ErrorMessage_LocationAccessUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read data from the NFC tag..
        /// </summary>
        public static string ErrorMessage_ParseNFC {
            get {
                return ResourceManager.GetString("ErrorMessage_ParseNFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to shoot or start recording. Make sure of the camera device&apos;s status..
        /// </summary>
        public static string ErrorMessage_shootingFailure {
            get {
                return ResourceManager.GetString("ErrorMessage_shootingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timeout. Make sure of the Wi-Fi connection and try again..
        /// </summary>
        public static string ErrorMessage_timeout {
            get {
                return ResourceManager.GetString("ErrorMessage_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string ExifExposureProgram_A {
            get {
                return ResourceManager.GetString("ExifExposureProgram_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulb.
        /// </summary>
        public static string ExifExposureProgram_Bulb {
            get {
                return ResourceManager.GetString("ExifExposureProgram_Bulb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High speed.
        /// </summary>
        public static string ExifExposureProgram_HighSpeed {
            get {
                return ResourceManager.GetString("ExifExposureProgram_HighSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string ExifExposureProgram_Landscape {
            get {
                return ResourceManager.GetString("ExifExposureProgram_Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string ExifExposureProgram_M {
            get {
                return ResourceManager.GetString("ExifExposureProgram_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string ExifExposureProgram_P {
            get {
                return ResourceManager.GetString("ExifExposureProgram_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        public static string ExifExposureProgram_Portrait {
            get {
                return ResourceManager.GetString("ExifExposureProgram_Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string ExifExposureProgram_S {
            get {
                return ResourceManager.GetString("ExifExposureProgram_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow speed.
        /// </summary>
        public static string ExifExposureProgram_SlowSpeed {
            get {
                return ResourceManager.GetString("ExifExposureProgram_SlowSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string ExifExposureProgram_Unknown {
            get {
                return ResourceManager.GetString("ExifExposureProgram_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudy.
        /// </summary>
        public static string ExifWBValue_Cloudy {
            get {
                return ResourceManager.GetString("ExifWBValue_Cloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool White Fluorescent.
        /// </summary>
        public static string ExifWBValue_CoolWhiteFluorescent {
            get {
                return ResourceManager.GetString("ExifWBValue_CoolWhiteFluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D50.
        /// </summary>
        public static string ExifWBValue_D50 {
            get {
                return ResourceManager.GetString("ExifWBValue_D50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D55.
        /// </summary>
        public static string ExifWBValue_D55 {
            get {
                return ResourceManager.GetString("ExifWBValue_D55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D65.
        /// </summary>
        public static string ExifWBValue_D65 {
            get {
                return ResourceManager.GetString("ExifWBValue_D65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D75.
        /// </summary>
        public static string ExifWBValue_D75 {
            get {
                return ResourceManager.GetString("ExifWBValue_D75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daylight.
        /// </summary>
        public static string ExifWBValue_Daylight {
            get {
                return ResourceManager.GetString("ExifWBValue_Daylight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daylight Fluorescent.
        /// </summary>
        public static string ExifWBValue_DaylightFluorescent {
            get {
                return ResourceManager.GetString("ExifWBValue_DaylightFluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayWhite Fluorescent.
        /// </summary>
        public static string ExifWBValue_DayWhiteFluorescent {
            get {
                return ResourceManager.GetString("ExifWBValue_DayWhiteFluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Weather.
        /// </summary>
        public static string ExifWBValue_FineWeather {
            get {
                return ResourceManager.GetString("ExifWBValue_FineWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        public static string ExifWBValue_Flash {
            get {
                return ResourceManager.GetString("ExifWBValue_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluorescent.
        /// </summary>
        public static string ExifWBValue_Fluorescent {
            get {
                return ResourceManager.GetString("ExifWBValue_Fluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO Studio Tungsten.
        /// </summary>
        public static string ExifWBValue_ISOStudioTungsten {
            get {
                return ResourceManager.GetString("ExifWBValue_ISOStudioTungsten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string ExifWBValue_Other {
            get {
                return ResourceManager.GetString("ExifWBValue_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shade.
        /// </summary>
        public static string ExifWBValue_Shade {
            get {
                return ResourceManager.GetString("ExifWBValue_Shade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Light A.
        /// </summary>
        public static string ExifWBValue_StandardLightA {
            get {
                return ResourceManager.GetString("ExifWBValue_StandardLightA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Light B.
        /// </summary>
        public static string ExifWBValue_StandardLightB {
            get {
                return ResourceManager.GetString("ExifWBValue_StandardLightB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Light C.
        /// </summary>
        public static string ExifWBValue_StandardLightC {
            get {
                return ResourceManager.GetString("ExifWBValue_StandardLightC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tungsten (Incandescent).
        /// </summary>
        public static string ExifWBValue_TungstenIncandescent {
            get {
                return ResourceManager.GetString("ExifWBValue_TungstenIncandescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string ExifWBValue_Unknown {
            get {
                return ResourceManager.GetString("ExifWBValue_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm White Fluorescent.
        /// </summary>
        public static string ExifWBValue_WarmWhiteFluorescent {
            get {
                return ResourceManager.GetString("ExifWBValue_WarmWhiteFluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Fluorescent.
        /// </summary>
        public static string ExifWBValue_WhiteFluorescent {
            get {
                return ResourceManager.GetString("ExifWBValue_WhiteFluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure compensation.
        /// </summary>
        public static string ExposureCompensation {
            get {
                return ResourceManager.GetString("ExposureCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure mode.
        /// </summary>
        public static string ExposureMode {
            get {
                return ResourceManager.GetString("ExposureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture priority.
        /// </summary>
        public static string ExposureMode_A {
            get {
                return ResourceManager.GetString("ExposureMode_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligent auto.
        /// </summary>
        public static string ExposureMode_iA {
            get {
                return ResourceManager.GetString("ExposureMode_iA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string ExposureMode_M {
            get {
                return ResourceManager.GetString("ExposureMode_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program auto.
        /// </summary>
        public static string ExposureMode_P {
            get {
                return ResourceManager.GetString("ExposureMode_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter priority.
        /// </summary>
        public static string ExposureMode_S {
            get {
                return ResourceManager.GetString("ExposureMode_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior auto.
        /// </summary>
        public static string ExposureMode_sA {
            get {
                return ResourceManager.GetString("ExposureMode_sA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin of Fibonacci spiral.
        /// </summary>
        public static string FibonacciSpiralOrigin {
            get {
                return ResourceManager.GetString("FibonacciSpiralOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash mode.
        /// </summary>
        public static string FlashMode {
            get {
                return ResourceManager.GetString("FlashMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string FlashMode_Auto {
            get {
                return ResourceManager.GetString("FlashMode_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear curtain sync..
        /// </summary>
        public static string FlashMode_RearSync {
            get {
                return ResourceManager.GetString("FlashMode_RearSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow sync..
        /// </summary>
        public static string FlashMode_SlowSync {
            get {
                return ResourceManager.GetString("FlashMode_SlowSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless.
        /// </summary>
        public static string FlashMode_Wireless {
            get {
                return ResourceManager.GetString("FlashMode_Wireless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip.
        /// </summary>
        public static string FlipMode {
            get {
                return ResourceManager.GetString("FlipMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string FlipMode_Off {
            get {
                return ResourceManager.GetString("FlipMode_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string FlipMode_On {
            get {
                return ResourceManager.GetString("FlipMode_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display focus frame.
        /// </summary>
        public static string FocusFrameDisplay {
            get {
                return ResourceManager.GetString("FocusFrameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus mode.
        /// </summary>
        public static string FocusMode {
            get {
                return ResourceManager.GetString("FocusMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF-C.
        /// </summary>
        public static string FocusMode_AFC {
            get {
                return ResourceManager.GetString("FocusMode_AFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF-S.
        /// </summary>
        public static string FocusMode_AFS {
            get {
                return ResourceManager.GetString("FocusMode_AFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MF.
        /// </summary>
        public static string FocusMode_Manual {
            get {
                return ResourceManager.GetString("FocusMode_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of assist lines.
        /// </summary>
        public static string FramingGridColor {
            get {
                return ResourceManager.GetString("FramingGridColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition assist.
        /// </summary>
        public static string FramingGrids {
            get {
                return ResourceManager.GetString("FramingGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosshairs.
        /// </summary>
        public static string Grid_Crosshairs {
            get {
                return ResourceManager.GetString("Grid_Crosshairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagonal.
        /// </summary>
        public static string Grid_Diagonal {
            get {
                return ResourceManager.GetString("Grid_Diagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibonacci spiral.
        /// </summary>
        public static string Grid_Fibonacci {
            get {
                return ResourceManager.GetString("Grid_Fibonacci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golden ratio.
        /// </summary>
        public static string Grid_GoldenRatio {
            get {
                return ResourceManager.GetString("Grid_GoldenRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule of thirds.
        /// </summary>
        public static string Grid_RuleOfThirds {
            get {
                return ResourceManager.GetString("Grid_RuleOfThirds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string Grid_Square {
            get {
                return ResourceManager.GetString("Grid_Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find the devide. Make sure that SSID of connected access point is that of your camera device&apos;s..
        /// </summary>
        public static string Guide_CantFindDevice {
            get {
                return ResourceManager.GetString("Guide_CantFindDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can invoke remote shutter with your phone&apos;s hardware shutter key..
        /// </summary>
        public static string Guide_DisplayTakeImageButtonSetting {
            get {
                return ResourceManager.GetString("Guide_DisplayTakeImageButtonSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to the camera to send focus frame information. This may cause performance issue on some devices..
        /// </summary>
        public static string Guide_FocusFrameDisplay {
            get {
                return ResourceManager.GetString("Guide_FocusFrameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw lines to assist photo composition..
        /// </summary>
        public static string Guide_FramingGrids {
            get {
                return ResourceManager.GetString("Guide_FramingGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze and display RGB histogram. This may cause performance issue on some devices..
        /// </summary>
        public static string Guide_Histogram {
            get {
                return ResourceManager.GetString("Guide_Histogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can touch your NFC enabled camera to detect Wi-Fi SSID and password..
        /// </summary>
        public static string Guide_NFC {
            get {
                return ResourceManager.GetString("Guide_NFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2M size images prior to the original by default..
        /// </summary>
        public static string Guide_PrioritizeOriginalSize {
            get {
                return ResourceManager.GetString("Guide_PrioritizeOriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive captured images and register them to the camera roll. (Disabled while interval recording is going on.).
        /// </summary>
        public static string Guide_ReceiveCapturedImage {
            get {
                return ResourceManager.GetString("Guide_ReceiveCapturedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe to start remote control..
        /// </summary>
        public static string Guide_StartLiveView {
            get {
                return ResourceManager.GetString("Guide_StartLiveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Wi-Fi settings and connect to your camera device..
        /// </summary>
        public static string Guide_WiFiNotEnabled {
            get {
                return ResourceManager.GetString("Guide_WiFiNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR remote.
        /// </summary>
        public static string InfraredRemoteControl {
            get {
                return ResourceManager.GetString("InfraredRemoteControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string IntervalCountPrefix {
            get {
                return ResourceManager.GetString("IntervalCountPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval shooting mode.
        /// </summary>
        public static string IntervalSetting {
            get {
                return ResourceManager.GetString("IntervalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval time.
        /// </summary>
        public static string IntervalTime {
            get {
                return ResourceManager.GetString("IntervalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string IntervalTime1 {
            get {
                return ResourceManager.GetString("IntervalTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string IntervalTimePrefix {
            get {
                return ResourceManager.GetString("IntervalTimePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --:--:--.
        /// </summary>
        public static string InvalidDuration {
            get {
                return ResourceManager.GetString("InvalidDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string IrRemoteSetting_Off {
            get {
                return ResourceManager.GetString("IrRemoteSetting_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string IrRemoteSetting_On {
            get {
                return ResourceManager.GetString("IrRemoteSetting_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO.
        /// </summary>
        public static string ISO {
            get {
                return ResourceManager.GetString("ISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please acknowledge that NO secret function is unlocked by purchasing these in-app items..
        /// </summary>
        public static string Message_Caution {
            get {
                return ResourceManager.GetString("Message_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation will encourage our development for continuous update!.
        /// </summary>
        public static string Message_Encourage {
            get {
                return ResourceManager.GetString("Message_Encourage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The picture has been captured successfully!.
        /// </summary>
        public static string Message_ImageCapture_Succeed {
            get {
                return ResourceManager.GetString("Message_ImageCapture_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The picture has been saved successfully!.
        /// </summary>
        public static string Message_ImageDL_Succeed {
            get {
                return ResourceManager.GetString("Message_ImageDL_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The picture has been saved with location info!.
        /// </summary>
        public static string Message_ImageDL_Succeed_withGeotag {
            get {
                return ResourceManager.GetString("Message_ImageDL_Succeed_withGeotag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-Fi password of your camera device has been saved to the clipboard!.
        /// </summary>
        public static string Message_NFC_succeed {
            get {
                return ResourceManager.GetString("Message_NFC_succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageCaption_error {
            get {
                return ResourceManager.GetString("MessageCaption_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened successfully!.
        /// </summary>
        public static string MessageCaption_NFC_Succeed {
            get {
                return ResourceManager.GetString("MessageCaption_NFC_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string MetaDataName_CameraModel {
            get {
                return ResourceManager.GetString("MetaDataName_CameraModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date taken.
        /// </summary>
        public static string MetaDataName_DateTime {
            get {
                return ResourceManager.GetString("MetaDataName_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure mode.
        /// </summary>
        public static string MetaDataName_ExposureProgram {
            get {
                return ResourceManager.GetString("MetaDataName_ExposureProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter Speed.
        /// </summary>
        public static string MetaDataName_ExposureTime {
            get {
                return ResourceManager.GetString("MetaDataName_ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F number.
        /// </summary>
        public static string MetaDataName_Fnumber {
            get {
                return ResourceManager.GetString("MetaDataName_Fnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focal length.
        /// </summary>
        public static string MetaDataName_FocalLength {
            get {
                return ResourceManager.GetString("MetaDataName_FocalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size.
        /// </summary>
        public static string MetaDataName_ImageSize {
            get {
                return ResourceManager.GetString("MetaDataName_ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO.
        /// </summary>
        public static string MetaDataName_Iso {
            get {
                return ResourceManager.GetString("MetaDataName_Iso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min..
        /// </summary>
        public static string Minute_Unit {
            get {
                return ResourceManager.GetString("Minute_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie format.
        /// </summary>
        public static string MovieFormat {
            get {
                return ResourceManager.GetString("MovieFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4.
        /// </summary>
        public static string MovieFormatMode_MP4 {
            get {
                return ResourceManager.GetString("MovieFormatMode_MP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAVC S.
        /// </summary>
        public static string MovieFormatMode_XAVCS {
            get {
                return ResourceManager.GetString("MovieFormatMode_XAVCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie quality.
        /// </summary>
        public static string MovieQuality {
            get {
                return ResourceManager.GetString("MovieQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ignore incorrect system prompt!!.
        /// </summary>
        public static string NFC_iiwake {
            get {
                return ResourceManager.GetString("NFC_iiwake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open source licenses.
        /// </summary>
        public static string OSSText {
            get {
                return ResourceManager.GetString("OSSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive captured pictures.
        /// </summary>
        public static string PostviewTransferSetting {
            get {
                return ResourceManager.GetString("PostviewTransferSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing camera state....
        /// </summary>
        public static string Progress_ChangingCameraState {
            get {
                return ResourceManager.GetString("Progress_ChangingCameraState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking storage information....
        /// </summary>
        public static string Progress_CheckingStorage {
            get {
                return ResourceManager.GetString("Progress_CheckingStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting selected contents....
        /// </summary>
        public static string Progress_DeletingSelectedContents {
            get {
                return ResourceManager.GetString("Progress_DeletingSelectedContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching contents....
        /// </summary>
        public static string Progress_FetchingContents {
            get {
                return ResourceManager.GetString("Progress_FetchingContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading camera roll images....
        /// </summary>
        public static string Progress_LoadingLocalContents {
            get {
                return ResourceManager.GetString("Progress_LoadingLocalContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening detail image....
        /// </summary>
        public static string Progress_OpeningDetailImage {
            get {
                return ResourceManager.GetString("Progress_OpeningDetailImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening movie stream....
        /// </summary>
        public static string Progress_OpeningMovieStream {
            get {
                return ResourceManager.GetString("Progress_OpeningMovieStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing connection....
        /// </summary>
        public static string ProgressMessageConnecting {
            get {
                return ResourceManager.GetString("ProgressMessageConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting connected camera device....
        /// </summary>
        public static string ProgressMessageDetectingDevice {
            get {
                return ResourceManager.GetString("ProgressMessageDetectingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching... {0} images to complete..
        /// </summary>
        public static string ProgressMessageFetching {
            get {
                return ResourceManager.GetString("ProgressMessageFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/kazyx/WPPMM.
        /// </summary>
        public static string RepoURL {
            get {
                return ResourceManager.GetString("RepoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Scene_Normal {
            get {
                return ResourceManager.GetString("Scene_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under water.
        /// </summary>
        public static string Scene_UnderWater {
            get {
                return ResourceManager.GetString("Scene_UnderWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        public static string SceneSelection {
            get {
                return ResourceManager.GetString("SceneSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self timer.
        /// </summary>
        public static string SelfTimer {
            get {
                return ResourceManager.GetString("SelfTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size to receive.
        /// </summary>
        public static string Setting_PostViewImageSize {
            get {
                return ResourceManager.GetString("Setting_PostViewImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritize original size images.
        /// </summary>
        public static string Setting_PrioritizeOriginalSize {
            get {
                return ResourceManager.GetString("Setting_PrioritizeOriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents sync settings.
        /// </summary>
        public static string SettingSection_ContentsSync {
            get {
                return ResourceManager.GetString("SettingSection_ContentsSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen settings.
        /// </summary>
        public static string SettingSection_Display {
            get {
                return ResourceManager.GetString("SettingSection_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo settings.
        /// </summary>
        public static string SettingSection_Image {
            get {
                return ResourceManager.GetString("SettingSection_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation mode.
        /// </summary>
        public static string ShootMode {
            get {
                return ResourceManager.GetString("ShootMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio rec.
        /// </summary>
        public static string ShootModeAudio {
            get {
                return ResourceManager.GetString("ShootModeAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval rec..
        /// </summary>
        public static string ShootModeIntervalStill {
            get {
                return ResourceManager.GetString("ShootModeIntervalStill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie rec.
        /// </summary>
        public static string ShootModeMovie {
            get {
                return ResourceManager.GetString("ShootModeMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still image rec.
        /// </summary>
        public static string ShootModeStill {
            get {
                return ResourceManager.GetString("ShootModeStill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SS.
        /// </summary>
        public static string ShutterSpeed {
            get {
                return ResourceManager.GetString("ShutterSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2M pixels.
        /// </summary>
        public static string Size2M {
            get {
                return ResourceManager.GetString("Size2M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string SizeOriginal {
            get {
                return ResourceManager.GetString("SizeOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steady shot.
        /// </summary>
        public static string SteadyShot {
            get {
                return ResourceManager.GetString("SteadyShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture resolution.
        /// </summary>
        public static string StillImageSize {
            get {
                return ResourceManager.GetString("StillImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still image quality.
        /// </summary>
        public static string StillQuality {
            get {
                return ResourceManager.GetString("StillQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine.
        /// </summary>
        public static string StillQuality_Fine {
            get {
                return ResourceManager.GetString("StillQuality_Fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAW+Jpeg.
        /// </summary>
        public static string StillQuality_RawAndJpeg {
            get {
                return ResourceManager.GetString("StillQuality_RawAndJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string StillQuality_Standard {
            get {
                return ResourceManager.GetString("StillQuality_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        public static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Focus.
        /// </summary>
        public static string TrackingFocusMode {
            get {
                return ResourceManager.GetString("TrackingFocusMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV system.
        /// </summary>
        public static string TvColorSystem {
            get {
                return ResourceManager.GetString("TvColorSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTSC.
        /// </summary>
        public static string TvColorSystemMode_NTSC {
            get {
                return ResourceManager.GetString("TvColorSystemMode_NTSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAL.
        /// </summary>
        public static string TvColorSystemMode_PAL {
            get {
                return ResourceManager.GetString("TvColorSystemMode_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top left corner.
        /// </summary>
        public static string UpperLeft {
            get {
                return ResourceManager.GetString("UpperLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top right corner.
        /// </summary>
        public static string UpperRight {
            get {
                return ResourceManager.GetString("UpperRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View angle.
        /// </summary>
        public static string ViewAngle {
            get {
                return ResourceManager.GetString("ViewAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deg..
        /// </summary>
        public static string ViewAngleUnit {
            get {
                return ResourceManager.GetString("ViewAngleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to playback movie content.
        /// </summary>
        public static string Viewer_FailedPlaybackMovie {
            get {
                return ResourceManager.GetString("Viewer_FailedPlaybackMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open detail image.
        /// </summary>
        public static string Viewer_FailedToOpenDetail {
            get {
                return ResourceManager.GetString("Viewer_FailedToOpenDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting contents to delete.
        /// </summary>
        public static string Viewer_Header_SelectingToDelete {
            get {
                return ResourceManager.GetString("Viewer_Header_SelectingToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting contents to download.
        /// </summary>
        public static string Viewer_Header_SelectingToDownload {
            get {
                return ResourceManager.GetString("Viewer_Header_SelectingToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to phone storage.
        /// </summary>
        public static string Viewer_MenuCopyToPhone {
            get {
                return ResourceManager.GetString("Viewer_MenuCopyToPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Viewer_MenuDelete {
            get {
                return ResourceManager.GetString("Viewer_MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string Viewer_MenuPlayback {
            get {
                return ResourceManager.GetString("Viewer_MenuPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable to access the function now.
        ///Please restart from shooting screen again..
        /// </summary>
        public static string Viewer_NoAvContentApi {
            get {
                return ResourceManager.GetString("Viewer_NoAvContentApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No storage seems to be attached.
        /// </summary>
        public static string Viewer_NoStorage {
            get {
                return ResourceManager.GetString("Viewer_NoStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading contents from new storage.
        /// </summary>
        public static string Viewer_RefreshAutomatically {
            get {
                return ResourceManager.GetString("Viewer_RefreshAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage access is not supported
        ///by your camera device.
        /// </summary>
        public static string Viewer_StorageAccessNotSupported {
            get {
                return ResourceManager.GetString("Viewer_StorageAccessNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the camera storage seems to be allowed only on the latest models....
        /// </summary>
        public static string Viewer_StorageAccessNotSupportedDetail {
            get {
                return ResourceManager.GetString("Viewer_StorageAccessNotSupportedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera storage.
        /// </summary>
        public static string Viewer_StorageCamera {
            get {
                return ResourceManager.GetString("Viewer_StorageCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory card storage seems to be detached.
        /// </summary>
        public static string Viewer_StorageDetached {
            get {
                return ResourceManager.GetString("Viewer_StorageDetached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone storage.
        /// </summary>
        public static string Viewer_StoragePhone {
            get {
                return ResourceManager.GetString("Viewer_StoragePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is closed by external error.
        /// </summary>
        public static string Viewer_StreamClosedByExternalCause {
            get {
                return ResourceManager.GetString("Viewer_StreamClosedByExternalCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content is not playable.
        /// </summary>
        public static string Viewer_UnplayableContent {
            get {
                return ResourceManager.GetString("Viewer_UnplayableContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for location info....
        /// </summary>
        public static string WaitingGeoposition {
            get {
                return ResourceManager.GetString("WaitingGeoposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string WB_Auto {
            get {
                return ResourceManager.GetString("WB_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudy.
        /// </summary>
        public static string WB_Cloudy {
            get {
                return ResourceManager.GetString("WB_Cloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color temperture.
        /// </summary>
        public static string WB_ColorTemperture {
            get {
                return ResourceManager.GetString("WB_ColorTemperture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string WB_Custom {
            get {
                return ResourceManager.GetString("WB_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom 1.
        /// </summary>
        public static string WB_Custom1 {
            get {
                return ResourceManager.GetString("WB_Custom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom 2.
        /// </summary>
        public static string WB_Custom2 {
            get {
                return ResourceManager.GetString("WB_Custom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom 3.
        /// </summary>
        public static string WB_Custom3 {
            get {
                return ResourceManager.GetString("WB_Custom3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daylight.
        /// </summary>
        public static string WB_DayLight {
            get {
                return ResourceManager.GetString("WB_DayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        public static string WB_Flash {
            get {
                return ResourceManager.GetString("WB_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluor. Cool white.
        /// </summary>
        public static string WB_Fluorescent_CoolWhite {
            get {
                return ResourceManager.GetString("WB_Fluorescent_CoolWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluor. Daylight.
        /// </summary>
        public static string WB_Fluorescent_DayLight {
            get {
                return ResourceManager.GetString("WB_Fluorescent_DayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluor. Day white.
        /// </summary>
        public static string WB_Fluorescent_DayWhite {
            get {
                return ResourceManager.GetString("WB_Fluorescent_DayWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluor. Warm white.
        /// </summary>
        public static string WB_Fluorescent_WarmWhite {
            get {
                return ResourceManager.GetString("WB_Fluorescent_WarmWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incandescent.
        /// </summary>
        public static string WB_Incandescent {
            get {
                return ResourceManager.GetString("WB_Incandescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shade.
        /// </summary>
        public static string WB_Shade {
            get {
                return ResourceManager.GetString("WB_Shade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White balance.
        /// </summary>
        public static string WhiteBalance {
            get {
                return ResourceManager.GetString("WhiteBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-Fi.
        /// </summary>
        public static string WifiSettingLauncherButtonText {
            get {
                return ResourceManager.GetString("WifiSettingLauncherButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearImage zoom.
        /// </summary>
        public static string ZoomMode_ClearImageDigital {
            get {
                return ResourceManager.GetString("ZoomMode_ClearImageDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optical only.
        /// </summary>
        public static string ZoomMode_Optical {
            get {
                return ResourceManager.GetString("ZoomMode_Optical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom setting.
        /// </summary>
        public static string ZoomSetting {
            get {
                return ResourceManager.GetString("ZoomSetting", resourceCulture);
            }
        }
    }
}
